version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: 0xmintyn-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/uploads:/app/uploads
      - ./Backend/mails:/app/mails
    networks:
      - 0xmintyn-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: 0xmintyn-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - 0xmintyn-network

networks:
  0xmintyn-network:
    driver: bridge
